### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mhsjlw** [dballard/cl-pack#2]
In the README it says it was released under MIT but in every file it says BSD? (also, by BSD do you mean BSD-3-Clause)

**Comment by dballard** [comment]
thanks. fixed
3 clause BSD as in
https://github.com/dballard/cl-pack/blob/master/LICENSE

**Comment by mhsjlw** [comment]
Awesome, thanks. Well I have you here, can this be published to quicklisp? I'd thought I'd ask permission before publishing it. If you want to, you have to replace ieee-floats with the quicklisp version, or, I can publish my version which already has it updated. It's up to you.

**Comment by mhsjlw** [comment]
Or if you don't want it published that's an option too, and I'll understand

**Comment by dballard** [comment]
can make a pull request with your changes. i'll accept
I'd love for this to be in quicklisp! thanks!

**Comment by dballard** [comment]
oh cool seems like i could. I merged your changes! 
Awesome, thanks so much!
And yes, please put up for inclusion in quicklisp!

**Comment by mhsjlw** [comment]
Thank you very much for being so cooperative! I've created a request here: https://github.com/quicklisp/quicklisp-projects/issues/1147

**Comment by mhsjlw** [comment]
cl-pack is now available in Quicklisp! Awesome!
