### ISSUE TITLE
Wrong format string in byte-to-2hex , missing a quote

### ISSUE THREAD

**Issue by Yehouda** [dballard/cl-pack#5]
In cl-pack.lisp, the function **byte-to-2hex** uses  a bad format string, because it misses a quote before the pad character 0. Instead of:
`(format nil "~2,0X" byte)`
It should be: 
`(format nil "~2,'0X" byte)`

This is defined here: 
http://www.lispworks.com/documentation/lw50/CLHS/Body/22_c.htm

With inline examples `~5,'0d` and `~5,'*d`. 

Gives an error when running `(cl-pack-test:test)`. After fixing it runs without a failure.

**Comment by dballard** [comment]
Interesting, has worked fine for me, I'm running SBCL 1.4.5 on ubuntu 18.04, what are you running

regardless, your proposed fix doesn't break it for me so I'll update it :)

**Comment by dballard** [comment]
fixed, updated

I am, very out of the lisp world these days, I did not that 4 other tests are failing for me?

https://github.com/dballard/cl-pack/issues/6

If you look, do any obvious fixes jump out to you?

**Comment by Yehouda** [comment]
Nothing jumps up. 

Is that using (cl-pack-test:test)? As I wrote, this doesn't fail on LispWorks with the fix. 
You can try doing (trace string=) to see what the first two failed tests actually compare.  On LispWorks I needed to load the test.lisp interpreted to actually see it, because the compiler transforms string= away.
